export type TFormData = {
  targetCountry?: string;
  language?: string;
  contentFormat?: string;
  emailType?: string;
  subjectLineGeneration?: string;
  subjectLineStyle?: string;
  outputFormat?: string;
  emailSequenceType?: string;
  noOfEmailsInSeq?: string;
  emailsInterval?: string;
  smsType?: string;
  smsSequence?: string;
  smsInterval?: string;
  smsSequenceObj?: string;
  hashtagInclusion?: string;
  numberOfDesiredHashtags?: string;
  articleType?: string;
  articleStructure?: string;
  noOfArticlesInSeries?: string;
  seriesStructure?: string;
  writingStyles?: string;
  targetAudiences?: string;
  communicationObjectives?: string;
  contentLengths?: string;
  elementsToInclude?: string[];
  aiModels?: string;
  urgencyLevels?: string;
  outputFormats?: string;
  offerDetails?: string;
  keywords?: string[];
};

//   smsSequence: string | null;
//   socialMediaHashtags: string | null;
//   blogArticleType: string | null;
//   articleStructure: string | null;
//   writingStyle: string | null;
//   targetAudience: string | null;
//   communicationObjective: string | null;
//   contentLength: string | null;
//   elementsToInclude: string | null;
//   aiModel: string | null;
//   urgencyLevel: string | null;
//   keywords: string | null;
//   outputFormat: string | null;
//   specificOfferInfo: string | null;
